<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-12-08T18:18:24Z" name="Suite" finished-at="2019-12-08T18:19:18Z" duration-ms="53399">
    <groups>
    </groups>
    <test started-at="2019-12-08T18:18:24Z" name="Test" finished-at="2019-12-08T18:19:18Z" duration-ms="53399">
      <class name="techm.techm1.test1">
        <test-method is-config="true" signature="launchDriver()[pri:0, instance:techm.techm1.test1@71def8f8]" started-at="2019-12-08T23:48:25Z" name="launchDriver" finished-at="2019-12-08T23:48:34Z" duration-ms="9628" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method signature="Test1()[pri:0, instance:techm.techm1.test1@71def8f8]" started-at="2019-12-08T23:48:34Z" name="Test1" finished-at="2019-12-08T23:48:41Z" duration-ms="7177" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method is-config="true" signature="launchDriver()[pri:0, instance:techm.techm1.test1@71def8f8]" started-at="2019-12-08T23:48:41Z" name="launchDriver" finished-at="2019-12-08T23:48:51Z" duration-ms="9559" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method signature="Test2()[pri:0, instance:techm.techm1.test1@71def8f8]" started-at="2019-12-08T23:48:51Z" name="Test2" finished-at="2019-12-08T23:49:07Z" duration-ms="16094" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method is-config="true" signature="launchDriver()[pri:0, instance:techm.techm1.test1@71def8f8]" started-at="2019-12-08T23:49:07Z" name="launchDriver" finished-at="2019-12-08T23:49:16Z" duration-ms="9307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method signature="Test3()[pri:0, instance:techm.techm1.test1@71def8f8]" started-at="2019-12-08T23:49:16Z" name="Test3" finished-at="2019-12-08T23:49:18Z" duration-ms="1611" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Google] but found [Expected title]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Google] but found [Expected title]
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at techm.techm1.test1.Test3(test1.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:715)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:907)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1237)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:51)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:85)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
      </class> <!-- techm.techm1.test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
